--changeset CreateDataBase: 1
CREATE sequence "QUADRINHOS".SQ_CLASSIFICATION START WITH 1 increment BY 1 nomaxvalue nominvalue cache 20 noorder;
CREATE sequence "QUADRINHOS".SQ_DESC_CLASS START WITH 1 increment BY 1 nomaxvalue nominvalue cache 20 noorder;
CREATE sequence "QUADRINHOS".SQ_URLS_UTIL START WITH 1 increment BY 1 nomaxvalue nominvalue cache 20 noorder;
CREATE sequence "QUADRINHOS".SQ_USERS START WITH 1 increment BY 1 nomaxvalue nominvalue cache 20 noorder;
CREATE sequence "QUADRINHOS".SQ_MENUS START WITH 1 increment BY 1 nomaxvalue nominvalue cache 20 noorder;
CREATE sequence "QUADRINHOS".SQ_CLASSIFICATION START WITH 1 increment BY 1 nomaxvalue nominvalue cache 20 noorder;
CREATE sequence "QUADRINHOS".SQ_GAME START WITH 1 increment BY 1 nomaxvalue nominvalue cache 20 noorder;
CREATE sequence "QUADRINHOS".SQ_PLAYER START WITH 1 increment BY 1 nomaxvalue nominvalue cache 20 noorder;
CREATE sequence "QUADRINHOS".SQ_CARD START WITH 1 increment BY 1 nomaxvalue nominvalue cache 20 noorder;

CREATE TABLE
    "QUADRINHOS".DESC_CLASS
    (
        VALUE NUMBER(2) NOT NULL,
        TYPE_CLASS VARCHAR2(50) NOT NULL,
        DESCRIPTION VARCHAR2(100),
        CONSTRAINT DESC_CLASS_PK PRIMARY KEY (VALUE, TYPE_CLASS)
    );

CREATE TABLE
    "QUADRINHOS".CLASSIFICATION
    (
        ID INTEGER NOT NULL,
        GENIUS CHAR(1),
        DURABILITY NUMBER(2) DEFAULT 0 NOT NULL,
        ENERGY NUMBER(2) DEFAULT 0 NOT NULL,
        INTELLIGENCE NUMBER(2) DEFAULT 0 NOT NULL,
        COMBAT NUMBER(2) DEFAULT 0 NOT NULL,
        SPEED NUMBER(2) DEFAULT 0 NOT NULL,
        STRENGTH NUMBER(2) DEFAULT 0 NOT NULL,
        CONSTRAINT CLASS_PK PRIMARY KEY (ID)
    );

CREATE TABLE
    "QUADRINHOS".URLS_UTIL
    (
        ID INTEGER NOT NULL,
        TYPE VARCHAR2(20) NOT NULL,
        URL VARCHAR2(300) NOT NULL,
        CONSTRAINT URLS_UTIL_PK PRIMARY KEY (ID)
    );
  
CREATE TABLE
    "QUADRINHOS".CREATOR
    (
        ID INTEGER NOT NULL,
        FIRST_NAME VARCHAR2(50),
        MIDDLE_NAME VARCHAR2(50),
        LAST_NAME VARCHAR2(50),
        SUFFIX VARCHAR2(100),
        FULL_NAME VARCHAR2(300),
        MODIFIED TIMESTAMP,
        PATH_THUMBNAIL VARCHAR2(300),
        CONSTRAINT CREATOR_PK PRIMARY KEY (ID)
    );

 CREATE TABLE
    "QUADRINHOS".COMIC
    (
        ID INTEGER NOT NULL,
        TITLE VARCHAR2(100) NOT NULL,
        DESCIPTION VARCHAR2(4000),
        VARIANT_DESCRIPTION VARCHAR2(4000),
        ISBN VARCHAR2(20),
        MODIFIED TIMESTAMP,
        PATH_THUMBNAIL VARCHAR2(300),
        FAVORITE CHAR(1) DEFAULT '0' NOT NULL,
        CONSTRAINT COMICS_PK PRIMARY KEY (ID)
    );

 CREATE TABLE
    "QUADRINHOS".SERIE
    (
        ID INTEGER NOT NULL,
        TITLE VARCHAR2(100) NOT NULL,
        DESCRIPTION VARCHAR2(4000),
        MODIFIED TIMESTAMP,
        PATH_THUMBNAIL VARCHAR2(300),
        FAVORITE CHAR(1) DEFAULT '0' NOT NULL,
        CONSTRAINT SERIES_PK PRIMARY KEY (ID)
    );

CREATE TABLE
    "QUADRINHOS".STORIE
    (
        ID INTEGER NOT NULL,
        TITLE VARCHAR2(100) NOT NULL,
        DESCRIPTION VARCHAR2(4000),
        MODIFIED TIMESTAMP,
        PATH_THUMBNAIL VARCHAR2(300),
        FAVORITE CHAR(1) DEFAULT '0' NOT NULL,
        CONSTRAINT STORIES_PK PRIMARY KEY (ID)
    );

CREATE TABLE
    "QUADRINHOS".EVENT
    (
        ID INTEGER NOT NULL,
        TITLE VARCHAR2(100) NOT NULL,
        DESCRIPTION VARCHAR2(4000),
        MODIFIED TIMESTAMP,
        GO TIMESTAMP,
        END TIMESTAMP,
        PATH_THUMBNAIL VARCHAR2(300),
        FAVORITE CHAR(1) DEFAULT '0' NOT NULL,
        CONSTRAINT EVENTS_PK PRIMARY KEY (ID)
    );

CREATE TABLE
    "QUADRINHOS".CHARACTER
    (
        ID INTEGER NOT NULL,
        NAME VARCHAR2(100) NOT NULL,
        DESCRIPTION VARCHAR2(4000),
        BIOGRAPHY VARCHAR2(4000),
        MODIFIED DATE,
        FAVORITE CHAR(1) DEFAULT '0' NOT NULL,
        PATH_THUMBNAIL VARCHAR2(300),
        CLASSIFICATION INTEGER NOT NULL,
        CONSTRAINT CHARACTER_PK PRIMARY KEY (ID),
        CONSTRAINT CHARACTER_FK1 FOREIGN KEY (CLASSIFICATION) REFERENCES "QUADRINHOS"."CLASSIFICATION" ON DELETE SET NULL
    );

CREATE TABLE
    "QUADRINHOS".CHARACTERS_COMICS
    (
        CHARACTER INTEGER NOT NULL,
        COMIC INTEGER NOT NULL,
        CONSTRAINT CHARACTERS_COMICS_PK PRIMARY KEY (CHARACTER, COMIC),
        CONSTRAINT CHARACTERS_COMICS_FK2 FOREIGN KEY (CHARACTER) REFERENCES "QUADRINHOS"."CHARACTER" ON DELETE SET NULL,
        CONSTRAINT CHARACTERS_COMICS_FK1 FOREIGN KEY (COMIC) REFERENCES "QUADRINHOS"."COMIC" ON DELETE SET NULL
    );

CREATE TABLE
    "QUADRINHOS".CHARACTERS_STORIES
    (
        CHARACTER INTEGER NOT NULL,
        STORIE INTEGER NOT NULL,
        CONSTRAINT CHARACTERS_STORIES_PK PRIMARY KEY (CHARACTER, STORIE),
        CONSTRAINT CHARACTERS_STORIES_FK2 FOREIGN KEY (CHARACTER) REFERENCES "QUADRINHOS"."CHARACTER" ON DELETE SET NULL,
        CONSTRAINT CHARACTERS_STORIES_FK1 FOREIGN KEY (STORIE) REFERENCES "QUADRINHOS"."STORIE" ON DELETE SET NULL
    );

CREATE TABLE
    "QUADRINHOS".CHARACTERS_SERIES
    (
        CHARACTER INTEGER NOT NULL,
        SERIE INTEGER NOT NULL,
        CONSTRAINT CHARACTERS_SERIES_PK PRIMARY KEY (CHARACTER, SERIE),
        CONSTRAINT CHARACTERS_SERIES_FK2 FOREIGN KEY (CHARACTER) REFERENCES "QUADRINHOS"."CHARACTER" ON DELETE SET NULL,
        CONSTRAINT CHARACTERS_SERIES_FK1 FOREIGN KEY (SERIE) REFERENCES "QUADRINHOS"."SERIE" ON DELETE SET NULL
    );

CREATE TABLE
    "QUADRINHOS".CHARACTERS_CREATORS
    (
        CHARACTER INTEGER NOT NULL,
        CREATOR INTEGER NOT NULL,
        CONSTRAINT CHARACTERS_CREATORS_PK PRIMARY KEY (CHARACTER, CREATOR),
        CONSTRAINT CHARACTERS_CREATORS_FK2 FOREIGN KEY (CHARACTER) REFERENCES "QUADRINHOS"."CHARACTER" ON DELETE SET NULL,
        CONSTRAINT CHARACTERS_CREATORS_FK1 FOREIGN KEY (CREATOR) REFERENCES "QUADRINHOS"."CREATOR" ON DELETE SET NULL
    );

CREATE TABLE
    "QUADRINHOS".COMICS_STORIES
    (
        COMIC INTEGER NOT NULL,
        STORIE INTEGER NOT NULL,
        CONSTRAINT COMICS_STORIES_PK PRIMARY KEY (COMIC, STORIE),
        CONSTRAINT COMICS_STORIES_FK1 FOREIGN KEY (COMIC) REFERENCES "QUADRINHOS"."COMIC" ON DELETE SET NULL,
        CONSTRAINT COMICS_STORIES_FK2 FOREIGN KEY (STORIE) REFERENCES "QUADRINHOS"."STORIE" ON DELETE SET NULL
    );

CREATE TABLE
    "QUADRINHOS".COMICS_EVENTS
    (
        COMIC INTEGER NOT NULL,
        EVENT INTEGER NOT NULL,
        CONSTRAINT COMICS_EVENTS_PK PRIMARY KEY (COMIC, EVENT),
        CONSTRAINT COMICS_EVENTS_FK1 FOREIGN KEY (COMIC) REFERENCES "QUADRINHOS"."COMIC" ON DELETE SET NULL,
        CONSTRAINT COMICS_EVENTS_FK2 FOREIGN KEY (EVENT) REFERENCES "QUADRINHOS"."EVENT" ON DELETE SET NULL
    );

CREATE TABLE
    "QUADRINHOS".COMICS_SERIES
    (
        COMIC INTEGER NOT NULL,
        SERIE INTEGER NOT NULL,
        CONSTRAINT COMICS_SERIES_PK PRIMARY KEY (COMIC, SERIE),
        CONSTRAINT COMICS_SERIES_FK1 FOREIGN KEY (COMIC) REFERENCES "QUADRINHOS"."COMIC" ON DELETE SET NULL,
        CONSTRAINT COMICS_SERIES_FK2 FOREIGN KEY (SERIE) REFERENCES "QUADRINHOS"."SERIE" ON DELETE SET NULL
    );

CREATE TABLE
    "QUADRINHOS".COMICS_CREATORS
    (
        COMIC INTEGER NOT NULL,
        CREATOR INTEGER NOT NULL,
        CONSTRAINT COMICS_CREATORS_PK PRIMARY KEY (COMIC, CREATOR),
        CONSTRAINT COMICS_CREATORS_FK1 FOREIGN KEY (COMIC) REFERENCES "QUADRINHOS"."COMIC" ON DELETE SET NULL,
        CONSTRAINT COMICS_CREATORS_FK2 FOREIGN KEY (CREATOR) REFERENCES "QUADRINHOS"."CREATOR" ON DELETE SET NULL
    );

CREATE TABLE
    "QUADRINHOS".SERIES_EVENTS
    (
        SERIE INTEGER NOT NULL,
        EVENT INTEGER NOT NULL,
        CONSTRAINT SERIES_EVENTS_PK PRIMARY KEY (SERIE, EVENT),
        CONSTRAINT SERIES_EVENTS_FK1 FOREIGN KEY (SERIE) REFERENCES "QUADRINHOS"."SERIE" ON DELETE SET NULL,
        CONSTRAINT SERIES_EVENTS_FK2 FOREIGN KEY (EVENT) REFERENCES "QUADRINHOS"."EVENT" ON DELETE SET NULL
    );

CREATE TABLE
    "QUADRINHOS".SERIES_STORIES
    (
        SERIE INTEGER NOT NULL,
        STORIE INTEGER NOT NULL,
        CONSTRAINT SERIES_STORIES_PK PRIMARY KEY (SERIE, STORIE),
        CONSTRAINT SERIES_STORIES_FK1 FOREIGN KEY (SERIE) REFERENCES "QUADRINHOS"."SERIE" ON DELETE SET NULL,
        CONSTRAINT SERIES_STORIES_FK2 FOREIGN KEY (STORIE) REFERENCES "QUADRINHOS"."STORIE" ON DELETE SET NULL
    );

CREATE TABLE
    "QUADRINHOS".SERIES_CREATORS
    (
        SERIE INTEGER NOT NULL,
        CREATOR INTEGER NOT NULL,
        CONSTRAINT SERIES_CREATORS_PK PRIMARY KEY (SERIE, CREATOR),
        CONSTRAINT SERIES_CREATORS_FK1 FOREIGN KEY (SERIE) REFERENCES "QUADRINHOS"."SERIE" ON DELETE SET NULL,
        CONSTRAINT SERIES_CREATORS_FK2 FOREIGN KEY (CREATOR) REFERENCES "QUADRINHOS"."CREATOR" ON DELETE SET NULL
    );

CREATE TABLE
    "QUADRINHOS".STORIES_EVENTS
    (
        STORIE INTEGER NOT NULL,
        EVENT INTEGER NOT NULL,
        CONSTRAINT STORIES_EVENTS_PK PRIMARY KEY (STORIE, EVENT),
        CONSTRAINT STORIES_EVENTS_FK1 FOREIGN KEY (STORIE) REFERENCES "QUADRINHOS"."STORIE" ON DELETE SET NULL,
        CONSTRAINT STORIES_EVENTS_FK2 FOREIGN KEY (EVENT) REFERENCES "QUADRINHOS"."EVENT" ON DELETE SET NULL
    );

CREATE TABLE
    "QUADRINHOS".STORIES_CREATORS
    (
        STORIE INTEGER NOT NULL,
        CREATOR INTEGER NOT NULL,
        CONSTRAINT STORIES_CREATORS_PK PRIMARY KEY (STORIE, CREATOR),
        CONSTRAINT STORIES_CREATORS_FK1 FOREIGN KEY (STORIE) REFERENCES "QUADRINHOS"."STORIE" ON DELETE SET NULL,
        CONSTRAINT STORIES_CREATORS_FK2 FOREIGN KEY (CREATOR) REFERENCES "QUADRINHOS"."CREATOR" ON DELETE SET NULL
    );

CREATE TABLE
    "QUADRINHOS".EVENTS_CREATORS
    (
        EVENT INTEGER NOT NULL,
        CREATOR INTEGER NOT NULL,
        CONSTRAINT EVENTS_CREATORS_PK PRIMARY KEY (EVENT, CREATOR),
        CONSTRAINT EVENTS_CREATORS_FK1 FOREIGN KEY (EVENT) REFERENCES "QUADRINHOS"."EVENT" ON DELETE SET NULL,
        CONSTRAINT EVENTS_CREATORS_FK2 FOREIGN KEY (CREATOR) REFERENCES "QUADRINHOS"."CREATOR" ON DELETE SET NULL
    );
    
CREATE TABLE
    "QUADRINHOS".MENUS
    (
        ID INTEGER NOT NULL,
        NAME_MENU VARCHAR(100) NOT NULL,
        DESCRIPTION VARCHAR2(100),
        ROUTE VARCHAR(100),
        ICON VARCHAR(50),
        HIDDEN CHAR(1) DEFAULT '0' NOT NULL,
        FAVORITE CHAR(1) DEFAULT '0' NOT NULL,
        CONSTRAINT MENUS_PK PRIMARY KEY (ID),
        CONSTRAINT MENUS_UN1 UNIQUE ("NAME_MENU")
    );
    
CREATE TABLE
    "QUADRINHOS".PROFILES
    (
        ID INTEGER NOT NULL,
        NAME_PROFILE VARCHAR(100) NOT NULL,        
        CONSTRAINT PROFILES_PK PRIMARY KEY (ID),
        CONSTRAINT PROFILES_UN1 UNIQUE ("NAME_PROFILE")
    );

CREATE TABLE
    "QUADRINHOS".PROFILE_MENUS
    (
        ID_PROFILE INTEGER NOT NULL,
        ID_MENU INTEGER NOT NULL,
        CONSTRAINT PROFILE_MENUS_PK PRIMARY KEY (ID_PROFILE, ID_MENU),
        CONSTRAINT PROFILE_MENUS_FK1 FOREIGN KEY (ID_PROFILE) REFERENCES "QUADRINHOS"."PROFILES" ON DELETE SET NULL,
        CONSTRAINT PROFILE_MENUS_FK2 FOREIGN KEY (ID_MENU) REFERENCES "QUADRINHOS"."MENUS" ON DELETE SET NULL
    );

CREATE TABLE 
    "QUADRINHOS".USERS 
    (
        ID INTEGER NOT NULL,
        NAME VARCHAR(300) NOT NULL, 
        DT_BIRTH DATE NOT NULL,
        SEX CHAR(1) NOT NULL,
        USER_ID VARCHAR(20) NOT NULL,
        EMAIL VARCHAR(300) NOT NULL,
        PASSWORD VARCHAR(20) NOT NULL,
        STATUS NUMBER(1) NOT NULL,
        CD_CONFIRMATION NUMBER(10) NOT NULL,
        CONSTRAINT USERS_PK PRIMARY KEY (ID),
        CONSTRAINT USERS_UN1 UNIQUE ("USER_ID"),
        CONSTRAINT USERS_UN2 UNIQUE ("EMAIL")
    );

CREATE TABLE 
    "QUADRINHOS".USERS_PROFILES 
    (
        ID_USER INTEGER NOT NULL,
        ID_PROFILE INTEGER NOT NULL,
        CONSTRAINT USERS_PROFILES_FK1 FOREIGN KEY (ID_USER) REFERENCES "QUADRINHOS"."USERS" ON DELETE SET NULL,
        CONSTRAINT USERS_PROFILES_FK2 FOREIGN KEY (ID_PROFILE) REFERENCES "QUADRINHOS"."PROFILES" ON DELETE SET NULL
    );
    
CREATE TABLE 
    "QUADRINHOS".CARDS
    (
         ID INTEGER NOT NULL,
         CHARACTER INTEGER NOT NULL,
         POSITION VARCHAR2(20),
         CONSTRAINT CARDS_PK PRIMARY KEY (ID),
         CONSTRAINT CARDS_FK1 FOREIGN KEY (CHARACTER) REFERENCES "QUADRINHOS"."CHARACTER"
    );
    
CREATE TABLE 
    "QUADRINHOS".GAME 
	(
		ID INTEGER NOT NULL,
		TIME_LEFT NUMBER,
		DATE_GAME DATE NOT NULL,
		ROUND_PLAYER INTEGER,
		STAGE VARCHAR2(10),
		CARDS_PER_PLAYER NUMBER,
		TIME_PLAYED NUMBER,
		CONSTRAINT GAME_PK PRIMARY KEY (ID)
	);

CREATE TABLE
    "QUADRINHOS".PLAYER
    (
         ID INTEGER NOT NULL, 
    	 USER_ID INTEGER NOT NULL,
         CARDS INTEGER NOT NULL,
         SOCORE NUMBER DEFAULT 0 NOT NULL,
         CONSTRAINT GAME_PLAYER_PK PRIMARY KEY (ID),
         CONSTRAINT PLAYER_FK1 FOREIGN KEY (USER_ID) REFERENCES "QUADRINHOS"."USERS",
         CONSTRAINT PLAYER_FK2 FOREIGN KEY (CARDS) REFERENCES "QUADRINHOS"."CARDS"
    );

CREATE TABLE
    "QUADRINHOS".PLAYER_CARDS
    (
    	 PLAYER INTEGER NOT NULL,
         CARD INTEGER NOT NULL,
         CONSTRAINT PLAYER_CARDS_FK1 FOREIGN KEY (PLAYER) REFERENCES "QUADRINHOS"."PLAYER",
         CONSTRAINT PLAYER_CARDS_FK2 FOREIGN KEY (CARD) REFERENCES "QUADRINHOS"."CARDS"
    );
    
CREATE TABLE
    "QUADRINHOS".GAME_PLAYER
    (
         PLAYER INTEGER NOT NULL,
         GAME INTEGER NOT NULL,
         CONSTRAINT GAME_PLAYER_FK1 FOREIGN KEY (PLAYER) REFERENCES "QUADRINHOS"."PLAYER",
         CONSTRAINT GAME_PLAYER_FK2 FOREIGN KEY (GAME) REFERENCES "QUADRINHOS"."GAME"
    );